language: java
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
jdk:
- oraclejdk8
script:
- cd binjr
- mvn clean package
branches:
  only:
  - master
deploy:
  provider: releases
  api_key:
    secure: XhcwY50xVkmpaitaoCuy8uldxp1EPY/bOUVCI0ej1LnTiP8Oxqv02uPOl69TCjRHlMYPx5xscUe8EGhgU0agH/3fGzNCdNdQs4Q9WLvgLyWXFOSh1YWVXvAkclxaQGr0cS4+ASDgxiX8m0FfTnBnCGyH1OJOnjiIWIdPLnfqCOYzK4xpWHmjPoolIudbZAm5j4x1Ailjd+McLMUNx1FTFbJBev1zvcoSMPwXA3DjrmnvOmJeuARNzZE3LOdWRqgSdQJK/y/Kq4NxMEQ4uwP6ceamlsmedBpQqCPStHCCchXRs0UdrVW9vwJpmyKj4+Mf5m0A17soVsyL5Bs/bLcYjqFL3utE157rxmIdd0dkvpgCEle5EplMfhFnNj9kvpjoAjO4aae6af1+PA6DJkfFiEc7qaHn3BNT2PJMtjs/QU8fz5jsggrAeCAjkg1njiGNBDzyK4MdyVfN+apnjUwEA8RPJKsLVbWdEdxyCWr1s6h6iDl6hxL/FIhv+DZFl1XMYvPSvbskAcWRtSErom8pOLw8DM8lP34LqGsVMWeZUJyzWO3pCXZ825ulM+Uyxn9j/ypDAQRYKD/4PGLFL03aCvxQNhV/nBc1gDGCiPe8AtC0kwy2QOvmU7y1MXvaSPylUMmjP7EpMOkyhtvHEpOFW3/LlN/Eb3i+FqGAR61dbR0=
  file: binjr.jar
  on:
    repo: fthevenet/binjr
