language: java
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
jdk:
- oraclejdk8
before_install: git clone -b travis `git config --get remote.origin.url` binjr/target/travis
script: "./binjr/scripts/build.sh"
env:
  global:
  - BINJR_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: sH9fhG7xsKMVf3vnFNH8bM902hG+AGLooDB0ZNBiTYl7/8VvmJxDKDNI+dMsf/xiZZdaS02uvAXOlVHaaGDeAlVz7wV24chcsTkxWmBqguMS/BSLrepM3Luucf0lhw5X4KAxGnyhmJKShM0+3Rh1FyCUWL7DO9vxJpTQYzR9wQ85+ta3+QHSa4i5Fa7tKgHJBj3q22FNPS8QT/4RCNor1AFERuBJaGXO1hAPaBUHA//lrPZJM/xP7VsM7aYRoLTZxL0ZtSS45VRFqmlf16I6Q/ATATSO786SsMFVOcuvVyi2UwsBivCZbEQGcct3YHDk5jj4MgDePD+FsNjmLhLGt/Wvx0peqwhuMTfcNC6otCVqmOrCoL4GbtYengllFkHqymzt+KQMNQ+AmWjorpb7Fl2JwmF9f2pPt3g7aFiDX/pJDWHOoi/XEFp6ppOwg6zsbb4wcwI8u7aX6Yuy1IkZg6jFfNibTV0u4XWGInxI1RsiSxvYdGiNkJgJdBkwcGr3m2j0HO6uP4iYZQIIkkVHhWZO84wm5V5wIfH8SE9oukVAjlu+msrAwjMVTjsjWxYWf/jelyMxl8bM3s5+cVGDmnuKgVOdvehWS10ltYhsSUoX7BpVscZ8g2538YeU+V9p1qZG5HEAmqezr1/XK3+liCW55ru0KCDZ0JyKtCQXJV4=
  - secure: YOZNvJp+WPFatm3bswgYH+GLTEzFSSqglWRgUPHyyX91a6FGB6v/KeP8GcJdkuycAMzkqB3sDDg9t9C4zNuNi1jI9T7XmR1nq4+37Kz13yxlgO+755+ipuw62mgelwk+AElBD4T37xkX+A8BIQsrM7Ug7PynH+2QuJg6c+94NMzkfMCwSBfsEArSQrX5rE2lLD6TDH50BF1zqZOiFr0UfzQN2WDtkKXY3O5MCUluLKBAgBlMYi9BAjJvBeK7QvcxOjPwLzC3Qz1D34JedmJT0QgTscvk2BlJ7DK/N66jP4K3ft2zv1ftb5jIAKXEV1rKWLk5R+Ug2K3KuSfTOV2mAni/ufJ8yW6OC3qGzDnPKV/wzY3fLO9ammm+m/72tOquHLl0hYifiDpE4nwtSTlbciGmpFKwzwXdyeGjPpp9M8tWSD8YFiTGDhNOGwjyLAtHCc0LRCVBfe1luw8aTq3sBKyHzx4IhWUVyvBoqvTgch/c1YalCW4++PwdYE3nkbPGjDBExlseHiNnPRxq0YxjUJoAL2jUBvAcAVWPIfJshxXbwElKY40oMTaT54OKmkz9PM/C3HNKITcSnk8wjGrBC8/YowB0e1SXfB0OiKq6kJ35IPc2FEGRpLxTKURCQbJHWNh7W6vq1GUuvvE6Wsz2hd4a2vCdBls1nUtxvaG2zLY=
  - secure: Wxq3O+Xp8U3Rbp7DTxrKdlL3sQpPLfyzQlh6mfeBW3iRCTFJgXRxFcHVRxSr8FWIbVsRUKithEQlx6cpnEYPbSOtTXjryecj/Pq3HTtV59PTP+EoybQD7dUsHuK0rWk+mBPXFLOauJahfwXjGDmAqZbAPvgTUibxoW2AJcotM0etXrNHKjMjw7UtaZPZAlTwZkepJvynh75qyNyqX3SuiPLfZaNOfGX7g8bIep67KeQMpEjDz5zh6eW+5kUzSaGw9tJNW+YT7BYZVhN3GJPVNvK9DahxAfnWUq9Jkjr94Lq0jrFYnxluT/v6DDoSt40qx+H1D+Yg1JVB87lkqxheTOHdAQAYB8VDMRWhQaIGRJXlEiucrfBbUUdGjIVBtpuh62WSH14fELPTRjMH4E3mAh4FklSD0OM4OZVkgpJfC7Lf5hCwf6z8c4SPbJBhkVhK6LMwoJGRjLFQDUZNU6i/rar71/xhwYi6LHuC3Ubw4f6bfNUgqBXWEPINdkNoxzXKlDEsNFyDsevSX5HQiFaEuLVs84pgfN+eByLncHz4T1opj7v+Uu6GE96iAKnjqChnqat2Sq7tMHgCdLERt7eSsSHPrQEgfphdlEU5g63r4IceLUD0IY2YiIW4h6eTz5350OgLtknY0knDrdx+tE/6yyDKqy5icFyHH8BOFyyfKxc=
deploy:
  provider: releases
  api_key:
    secure: q13R8owl5kImv591zcDi+DkcADA5ghc0uqjqHbxxFPPABl/hroSGrTJ/xubvWZ1Ta6YGT0we9+/vNOuPEqAnfy3FhqE3ZREZytGoE5dCEewowgNidKu1OLhMYJD3QnEsrW8mIyLSwBk9hEBToQuD2ZXTf+zWfVenBdvUAP1WBWbXooLo/+RiFnTK1t3dx7206EPIhWQatm+PXzR/GtXC9B1h36XUPgscdkuDiTSrKFxxIZUUAMC4l1lyIZwlqrJG/sbypKsUH3V+JTh0W8VUeobNJ8l9D/7ez1osUxBC4CNnAlGAf5r0pC2lLwh/P4g0jPiMrekGFs2yvFlNe6RPHAZeZCRZXmXzkDLq23KpU/oRw60CR+GVrs+HOM8uObtjMhIeRpCJQwqQYlKqHJd3/169CZo4FcwRfTFGEZMYswopsBY5zLgczHeZ5aaoRPzRig7oHEImqMMv3o/WTHbrjJtdjZmeWkB/Zzr2zcWACRu80vijSLBecyrkIqaf9Bl8uh0dsp++OQXMNf4j29AMTY+tV0GaINrgzts7OtQudEGTfy3hBSy2XNJ+/vISwAs6u1xWNzjZWUDshK/tifcaZ8HwIk6WuLAXmzo/ogmH3xhiO6AE/6qhQLs2F0VEwEagZCLKzB7sNm4915E0GQB8jNJIpLDaXxCt0yBP1sa5Hkw=
  file: "/home/travis/build/fthevenet/binjr/binjr/target/binjr.jar"
  skip_cleanup: true
  overwrite: true
  name: binjr $TRAVIS_TAG
  on:
    tags: true
    all_branches: true
