language: java
sudo: false
#addons:
#  apt:
#    packages:
#    - oracle-java8-installer
jdk:
- oraclejdk8
before_install: git clone -b travis `git config --get remote.origin.url` binjr/target/travis
script:
- cd binjr
- mvn clean package
#branches:
           #  only:
           #  - master
env:
  global:
    secure: sH9fhG7xsKMVf3vnFNH8bM902hG+AGLooDB0ZNBiTYl7/8VvmJxDKDNI+dMsf/xiZZdaS02uvAXOlVHaaGDeAlVz7wV24chcsTkxWmBqguMS/BSLrepM3Luucf0lhw5X4KAxGnyhmJKShM0+3Rh1FyCUWL7DO9vxJpTQYzR9wQ85+ta3+QHSa4i5Fa7tKgHJBj3q22FNPS8QT/4RCNor1AFERuBJaGXO1hAPaBUHA//lrPZJM/xP7VsM7aYRoLTZxL0ZtSS45VRFqmlf16I6Q/ATATSO786SsMFVOcuvVyi2UwsBivCZbEQGcct3YHDk5jj4MgDePD+FsNjmLhLGt/Wvx0peqwhuMTfcNC6otCVqmOrCoL4GbtYengllFkHqymzt+KQMNQ+AmWjorpb7Fl2JwmF9f2pPt3g7aFiDX/pJDWHOoi/XEFp6ppOwg6zsbb4wcwI8u7aX6Yuy1IkZg6jFfNibTV0u4XWGInxI1RsiSxvYdGiNkJgJdBkwcGr3m2j0HO6uP4iYZQIIkkVHhWZO84wm5V5wIfH8SE9oukVAjlu+msrAwjMVTjsjWxYWf/jelyMxl8bM3s5+cVGDmnuKgVOdvehWS10ltYhsSUoX7BpVscZ8g2538YeU+V9p1qZG5HEAmqezr1/XK3+liCW55ru0KCDZ0JyKtCQXJV4=
deploy:
  provider: releases
  api_key:
    secure: q13R8owl5kImv591zcDi+DkcADA5ghc0uqjqHbxxFPPABl/hroSGrTJ/xubvWZ1Ta6YGT0we9+/vNOuPEqAnfy3FhqE3ZREZytGoE5dCEewowgNidKu1OLhMYJD3QnEsrW8mIyLSwBk9hEBToQuD2ZXTf+zWfVenBdvUAP1WBWbXooLo/+RiFnTK1t3dx7206EPIhWQatm+PXzR/GtXC9B1h36XUPgscdkuDiTSrKFxxIZUUAMC4l1lyIZwlqrJG/sbypKsUH3V+JTh0W8VUeobNJ8l9D/7ez1osUxBC4CNnAlGAf5r0pC2lLwh/P4g0jPiMrekGFs2yvFlNe6RPHAZeZCRZXmXzkDLq23KpU/oRw60CR+GVrs+HOM8uObtjMhIeRpCJQwqQYlKqHJd3/169CZo4FcwRfTFGEZMYswopsBY5zLgczHeZ5aaoRPzRig7oHEImqMMv3o/WTHbrjJtdjZmeWkB/Zzr2zcWACRu80vijSLBecyrkIqaf9Bl8uh0dsp++OQXMNf4j29AMTY+tV0GaINrgzts7OtQudEGTfy3hBSy2XNJ+/vISwAs6u1xWNzjZWUDshK/tifcaZ8HwIk6WuLAXmzo/ogmH3xhiO6AE/6qhQLs2F0VEwEagZCLKzB7sNm4915E0GQB8jNJIpLDaXxCt0yBP1sa5Hkw=
  file: "/binjr/target/binjr.jar"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    all_branches: true
