version: '{build}'

environment:
  GITHUB_TOKEN:
    secure: 4vpPlabt2OKA/pyJKSZUr3KJg8y0uJFnzf/kTmVUTCPIb9Q3fpjED+1LEXHYQ4UY
  SCM_USERNAME:
    secure: 8BjoFIdSfcFM5UNtivbS5w==

branches:

  only:

  - master

only_commits:

  message: /\[maven-release-plugin\] prepare release/

build_script:

- cmd: >-

    setx PATH "%WIX%;%PATH%"

    echo %PATH%

    set BINJR_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%

    git clone -b travis https://github.com/fthevenet/binjr.git binjr/target/travis

    cd binjr

    mvn clean deploy --settings "./target/travis/settings.xml" -P buildNativeBundles
