version: '{build}'

image: Visual Studio 2017

environment:
  GITHUB_TOKEN:
    secure: hp0jiQjq4o0cTcg9leeZ9sNq3FdEGkq1sNe8sDj9fTKOuQDn+1IN02bPoAOL9tBX

install:
-
  ps: |-
    $ENV:CURRENT_BRANCH=$ENV:APPVEYOR_REPO_BRANCH
    $ENV:JAVA_HOME="C:\Program Files\Java\jdk11"
    $ENV:PATH="$ENV:JAVA_HOME\bin;$ENV:PATH;$ENV:WIX\bin"
    $ENV:BINJR_BUILD_NUMBER=$ENV:APPVEYOR_BUILD_NUMBER

for:
-
  branches:
    only:
      - master

  build_script:
  - cmd: .\gradlew.bat packageDistribution

-
  branches:
    only:
    - release

  build_script:
  - cmd: .\gradlew.bat githubRelease
